#!/bin/bash
# Install dependencies and Marzban
#warna hijau
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
export PINK='\033[0;35m'
export YELLOW='\033[0;33m'

echo -e "${GREEN}♻️ Checking Ticket Masuk...${NC}"
sleep 3
clear 

mkdir -p /etc/data

# Mendapatkan IP publik pengguna
user_ip=$(curl -s https://ipinfo.io/ip)

# Meminta nama client dan memvalidasi
while true; do
    read -rp $'\033[0;32mMasukkan Nama Client:\033[0m ' client_name

    # Validasi Nama Client (misalnya tidak kosong dan hanya huruf)
    if [[ -z "$client_name" ]]; then
        echo "Nama Client tidak boleh kosong. Silakan masukkan kembali."
        continue
    elif [[ ! "$client_name" =~ ^[A-Za-z]+$ ]]; then
        echo "Nama Client hanya boleh berisi huruf. Silakan masukkan kembali."
        continue
    fi

    # Menggunakan curl untuk memeriksa apakah client_name ada dalam file permission.txt
    permission_file=$(curl -s https://raw.githubusercontent.com/helehsemvakwkwk/viavia/main/sholatbro.txt)
    if echo "$permission_file" | grep -q -i "$client_name"; then
        exp_date=$(echo "$permission_file" | grep -i "$client_name" | awk '{print $4}')
        echo "Client Name accepted... Let's go..."
        break
    else
        echo "Sorry beb, IP kamu belum terdaftar di database saya !!!"
        rm -f /root/siti # Ganti dengan path yang sesuai ke file installer
        exit 1
    fi
done

echo -e "${GREEN}Sedang Melanjutkan proses...${NC}"
sleep 2

colorized_echo() {
    local color=$1
    local text=$2
    
    case $color in
        "red")
        printf "\e[91m${text}\e[0m\n";;
        "green")
        printf "\e[92m${text}\e[0m\n";;
        "yellow")
        printf "\e[93m${text}\e[0m\n";;
        "blue")
        printf "\e[94m${text}\e[0m\n";;
        "magenta")
        printf "\e[95m${text}\e[0m\n";;
        "cyan")
        printf "\e[96m${text}\e[0m\n";;
        *)
            echo "${text}"
        ;;
    esac
}

echo -e "${GREEN}Mengunduh dan menginstal dependensi...${NC}"
sleep 2

# Telegram Bot API details
TOKEN="6234184002:AAEiSorPqtITst6I6tKocM4wtzh367dyeJA"
CHAT_ID="5044190184"

# Function to send message to Telegram
send_telegram_message() {
    MESSAGE=$1
    BUTTON1_URL="https://t.me/kangbacox"
    BUTTON2_URL="https://patunganvps.net"
    BUTTON_TEXT1="My Lord 😎"
    BUTTON_TEXT2="Cek Server 🐳"

    RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
        -d chat_id="$CHAT_ID" \
        -d parse_mode="MarkdownV2" \
        -d text="$MESSAGE" \
        -d reply_markup='{
            "inline_keyboard": [
                [{"text": "'"$BUTTON_TEXT1"'", "url": "'"$BUTTON1_URL"'"}, {"text": "'"$BUTTON_TEXT2"'", "url": "'"$BUTTON2_URL"'"}]
            ]
        }')

    # Print the response using jq to pretty-print
    echo "$RESPONSE" | jq .
}

# Check if the script is run as root
if [ "$(id -u)" != "0" ]; then
    colorized_echo red "Error: Skrip ini harus dijalankan sebagai root."
    exit 1
fi

# Check supported operating system
supported_os=false

if [ -f /etc/os-release ]; then
    os_name=$(grep -E '^ID=' /etc/os-release | cut -d= -f2)
    os_version=$(grep -E '^VERSION_ID=' /etc/os-release | cut -d= -f2 | tr -d '"')

    if [ "$os_name" == "debian" ] && [ "$os_version" == "11" ]; then
        supported_os=true
    elif [ "$os_name" == "ubuntu" ] && [ "$os_version" == "20.04" ]; then
        supported_os=true
    fi
fi
apt install sudo curl -y
if [ "$supported_os" != true ]; then
    colorized_echo red "Error: Skrip ini hanya support di Debian 11 dan Ubuntu 20.04. Mohon gunakan OS yang di support."
    exit 1
fi

# Fungsi untuk menambahkan repo Debian 11
addDebian11Repo() {
    echo "#mirror_kambing-sysadmind deb11
deb http://kartolo.sby.datautama.net.id/debian bullseye main contrib non-free
deb http://kartolo.sby.datautama.net.id/debian bullseye-updates main contrib non-free
deb http://kartolo.sby.datautama.net.id/debian-security bullseye-security main contrib non-free" | sudo tee /etc/apt/sources.list > /dev/null
}

# Fungsi untuk menambahkan repo Ubuntu 20.04
addUbuntu2004Repo() {
    echo "#mirror buaya klas 20.04
deb https://buaya.klas.or.id/ubuntu/ focal main restricted universe multiverse
deb https://buaya.klas.or.id/ubuntu/ focal-updates main restricted universe multiverse
deb https://buaya.klas.or.id/ubuntu/ focal-security main restricted universe multiverse
deb https://buaya.klas.or.id/ubuntu/ focal-backports main restricted universe multiverse
deb https://buaya.klas.or.id/ubuntu/ focal-proposed main restricted universe multiverse" | sudo tee /etc/apt/sources.list > /dev/null
}

# Mendapatkan informasi kode negara dan OS
COUNTRY_CODE=$(curl -s https://ipinfo.io/country)
OS=$(lsb_release -si)

# Pemeriksaan IP Indonesia
if [[ "$COUNTRY_CODE" == "ID" ]]; then
    colorized_echo green "IP Indonesia terdeteksi, menggunakan repositories lokal Indonesia !"
    # Menanyakan kepada pengguna apakah ingin menggunakan repo lokal atau repo default
    colorized_echo magenta "✩━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━✩"
    read -p "Apakah Anda ingin menggunakan repo lokal Indonesia? (y/n): " use_local_repo
    colorized_echo magenta "✩━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━✩"
    if [[ "$use_local_repo" == "y" || "$use_local_repo" == "Y" ]]; then
        # Pemeriksaan OS untuk menambahkan repo yang sesuai
        case "$OS" in
            Debian)
                VERSION=$(lsb_release -sr)
                if [ "$VERSION" == "11" ]; then
                    addDebian11Repo
                else
                    colorized_echo red "Versi Debian ini tidak didukung."
                fi
                ;;
            Ubuntu)
                VERSION=$(lsb_release -sr)
                if [ "$VERSION" == "20.04" ]; then
                    addUbuntu2004Repo
                else
                    colorized_echo red "Versi Ubuntu ini tidak didukung."
                fi
                ;;
            *)
                colorized_echo red "Sistem Operasi ini tidak didukung."
                ;;
        esac
    else
        colorized_echo yellow "Menggunakan repo bawaan VM."
        # Tidak melakukan apa-apa, sehingga repo bawaan VM tetap digunakan
    fi
else
    colorized_echo magenta "✩━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━✩"
    colorized_echo yellow "❖ IP VPS anda di luar negara Indonesia."
    colorized_echo magenta "✩━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━✩"
    # Lanjutkan dengan repo bawaan OS
fi
mkdir -p /etc/data

#domain
read -rp "$(echo -e "Masukkan Domain ${GREEN}( wajib pointing dulu )${NC}: ")" domain
echo "$domain" > /etc/data/domain
domain=$(cat /etc/data/domain)

#email
read -rp "$(echo -e "➣ Masukkan Email anda ${GREEN}( ex: skt@gmail.com )${NC}: ")" email

#username
while true; do
    read -rp "$(echo -e "➣ Masukkan Username Panel ${GREEN}( hanya huruf dan angka )${NC}: ")" userpanel

    # Memeriksa apakah userpanel hanya mengandung huruf dan angka
    if [[ ! "$userpanel" =~ ^[A-Za-z0-9]+$ ]]; then
        echo "UsernamePanel hanya boleh berisi huruf dan angka. Silakan masukkan kembali."
    elif [[ "$userpanel" =~ [Aa][Dd][Mm][Ii][Nn] ]]; then
        echo "UsernamePanel tidak boleh mengandung kata 'admin'. Silakan masukkan kembali."
    else
        echo "$userpanel" > /etc/data/userpanel
        break
    fi
done

read -rp "$(echo -e "➣ Masukkan Password Panel ${GREEN}( buat dashboard )${NC}: ")" passpanel
echo "$passpanel" > /etc/data/passpanel

# Function to validate port input
while true; do
  read -rp "$(echo -e "➣ Masukkan Default Port untuk Marzban Dashboard GUI ${GREEN}( Disarankan 7879 / 6969 )${NC}: ")" port

  if [[ "$port" -eq 443 || "$port" -eq 80 ]]; then
    echo -e "\e[91mPort $port tidak valid. Silakan isi dengan port selain 443 atau 80.\e[0m"
  else
    echo "Port yang Anda masukkan adalah: $port"
    break
  fi
done

#Preparation
#install dependient template bot
clear
cd;
echo -e "${YELLOW}🤖 Sabar beb, Sedang loading hehe...${NC}"
echo -e "${YELLOW}☠️ Ada impostor dinegara kita...${NC}"
echo -e "${GREEN}⠀⠀
⠀⠀⠈⠙⣿⣧⣶⣿⠿⣧⣴⣿⢻⡉⠀⢀⣠⣴⣾⡟⠿⠃⠁⣠⣤⡶⣾⡟⠅⠀⣀⡄⠀⣾⢸⣿⣏⢻⢶⣦⣤⣤⣄⢶⣾⣿⣡⣤⡄⠀
⠀⠀⣠⣞⣋⣿⣿⣾⣿⡿⡛⣹⡟⣤⢰⡿⠟⠉⣀⣀⣤⣤⡠⠙⢁⣾⡿⠂⠀⣿⠟⣁⠀⣹⠀⣹⣿⡟⣼⣿⣿⣌⣿⣞⣿⣿⠁⠀⠀⠀
⠀⢠⡿⢛⢟⣿⣿⣿⣿⣿⣿⡟⣼⣿⣟⢓⠛⣿⣏⣿⣵⣗⣵⣴⣿⢟⡵⣣⣼⣿⢟⣵⣶⢻⣶⣿⠀⠀⣈⢻⣿⣿⣿⢿⣾⢿⣧⠀⠀⠀
⠀⠘⠃⢸⣿⡾⣿⣿⣿⣿⣯⣿⣿⣿⣶⣿⣿⣟⣾⡿⣫⣿⣿⣿⣽⣿⣿⣿⣿⢫⣾⣿⣿⣿⣿⣿⣴⡆⣻⣿⡏⣿⢻⣧⣿⡿⣿⡆⠀⠀
⠀⠀⠀⠜⣿⣾⢿⣿⣿⣿⣾⣿⣿⣿⣿⣿⣿⣭⣿⣖⣿⢿⣿⡿⣿⣿⣿⡿⢡⢯⣿⣿⣿⣿⣿⣿⣿⣧⡿⣾⣷⣿⣿⢿⣿⡇⠉⠁⠀⠀
⠀⠀⠀⠀⣿⣥⣾⣿⣿⣿⣿⣿⣿⣿⡇⣭⣿⣿⣿⣿⠃⠞⠟⣸⣿⠏⣸⣧⣀⠿⢿⣿⣿⣟⣿⣿⣿⣿⣽⣿⢿⣿⣿⣿⣿⠁⠀⠀⠀⠀
⠀⠀⠀⠈⠛⣹⣿⣿⣿⣿⢿⣿⣿⣿⣿⣿⣟⣿⣿⡿⢶⣦⣄⣿⠏⠀⣿⣟⣿⣶⠾⣿⣟⣋⣛⣿⣿⣿⣿⡇⣻⣿⣿⣿⡏⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠟⠛⠫⣿⣿⣿⣿⣿⡿⣧⠛⣿⠛⣿⣿⣿⣷⡌⠹⡟⠀⡀⠉⡟⠋⢠⣾⣿⣿⣿⡟⣿⣿⣿⣿⢀⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠘⠋⣾⣷⣿⣿⣧⠙⠀⠙⢣⠝⠛⠋⣽⣷⢦⠇⠀⠀⠘⠁⣤⣾⣿⠝⠛⠉⠘⢻⣿⣿⢿⣼⣷⡟⢻⣷⠉⠀⡀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠐⠟⢻⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⠀⠀⠀⢈⠛⠀⠀⠀⠀⠀⣾⠟⠀⢸⣷⣿⡇⠀⠛⠀⠀⠁⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠁⠀⢹⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠂⠀⠀⠀⠀⢠⣿⣿⣿⡧⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠆⠀⠀⠀⠀⠀⠀⠈⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⢻⡿⠈⠁⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣇⠀⠀⠀⠀⠀⠀⠀⠀⠲⣄⠀⡄⠖⠀⠀⠀⠀⠀⠀⠀⠀⣼⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⣀⠀⠀⣠⣾⣿⠁⠀⠀⠀⠀⠀⣀⡄⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⢻⣆⠀⠛⠁⠶⣶⣶⣶⣶⣶⣶⡶⠆⠘⠋⣠⡾⢫⣾⡟⠀⠀⠀⠀⠀⠐⠉⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠛⠀⠙⣷⡀⠀⠀⠙⠛⠛⠛⠛⠋⠁⠀⢀⣴⠋⠀⣾⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣿⣰⣦⡀⠸⣿⣦⡀⠀⠀⠀⠀⠀⠀⢀⣴⡟⠁⠀⠐⢻⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣾⣿⣿⣿⡄⢺⣿⡄⠹⣿⠻⢦⣤⣤⣤⣤⣶⣿⡟⢀⣀⠀⠀⢸⣿⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢀⣠⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣮⣿⣿⡀⠹⡷⣦⣀⡀⡀⢸⣿⠏⢠⣾⣿⠀⠀⣾⣿⣿⣿⣿⣶⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀
⣀⣤⣴⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠘⣷⣻⡟⠀⡼⠁⣴⣿⣿⣯⣥⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⣀⠀⠀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣯⣿⣤⣤⣤⣬⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⣄
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
${NC}"
apt-get update -y >/dev/null 2>&1
apt-get install figlet toilet lolcat -y >/dev/null 2>&1
apt-get install ruby -y >/dev/null 2>&1
# Install lolcat gem without confirmation
gem install lolcat >/dev/null 2>&1
apt install sqlite3 -y
apt install -y pip
pip install requests==2.31.0
pip install colorama
pip3 install python-telegram-bot==13.7

#Remove unused Module
apt-get -y --purge remove samba*;
apt-get -y --purge remove apache2*;
apt-get -y --purge remove sendmail*;
apt-get -y --purge remove bind9*;

#install bbr
echo 'fs.file-max = 500000
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 4096
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mem = 25600 51200 102400
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.core.rmem_max = 4000000
net.ipv4.tcp_mtu_probing = 1
net.ipv4.ip_forward = 1
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1' >> /etc/sysctl.conf
sysctl -p;

#install toolkit
apt-get install libio-socket-inet6-perl libsocket6-perl libcrypt-ssleay-perl libnet-libidn-perl perl libio-socket-ssl-perl libwww-perl libpcre3 libpcre3-dev zlib1g-dev dbus iftop zip unzip wget net-tools curl nano sed screen gnupg gnupg1 bc apt-transport-https build-essential dirmngr dnsutils sudo at htop iptables bsdmainutils cron lsof lnav -y

#Set Timezone GMT+7
timedatectl set-timezone Asia/Jakarta;

#Install Marzban
sudo bash -c "$(curl -sL https://github.com/GawrAme/Marzban-scripts/raw/master/marzban.sh)" @ install

#Install Subs
wget -N -P /var/lib/marzban/templates/subscription/  https://raw.githubusercontent.com/raffasyaa/semvak-subs/master/template-01/index.html

#install env
wget -O /opt/marzban/.env "https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/env"

#install core Xray & Assets folder
mkdir -p /var/lib/marzban/assets
mkdir -p /var/lib/marzban/core
wget -O /var/lib/marzban/core/xray.zip "https://github.com/XTLS/Xray-core/releases/download/v1.8.16/Xray-linux-64.zip"
cd /var/lib/marzban/core && unzip xray.zip && chmod +x xray
cd

#profile
echo -e 'profile' >> /root/.profile
wget -O /usr/local/bin/profile "https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/profile";
chmod +x /usr/local/bin/profile

#install compose
wget -O /opt/marzban/docker-compose.yml "https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/docker-compose.yml"

#Install VNSTAT
apt -y install vnstat
/etc/init.d/vnstat restart
apt -y install libsqlite3-dev
wget https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/vnstat-2.6.tar.gz
tar zxvf vnstat-2.6.tar.gz
cd vnstat-2.6
./configure --prefix=/usr --sysconfdir=/etc && make && make install 
cd
chown vnstat:vnstat /var/lib/vnstat -R
systemctl enable vnstat
/etc/init.d/vnstat restart
rm -f /root/vnstat-2.6.tar.gz 
rm -rf /root/vnstat-2.6

#Install Speedtest
curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
sudo apt-get install speedtest -y

#install nginx
mkdir -p /var/log/nginx
touch /var/log/nginx/access.log
touch /var/log/nginx/error.log
wget -O /opt/marzban/nginx.conf "https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/nginx.conf"
wget -O /opt/marzban/default.conf "https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/vps.conf"
wget -O /opt/marzban/xray.conf "https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/xray.conf"
mkdir -p /var/www/html
wget -O /var/www/html/index.html "https://raw.githubusercontent.com/raffasyaa/semvak-subs/main/propil.html"

#install socat
apt install iptables -y
apt install curl socat xz-utils wget apt-transport-https gnupg gnupg2 gnupg1 dnsutils lsb-release -y 
apt install socat cron bash-completion -y

#install cert
curl https://get.acme.sh | sh -s email=$email
/root/.acme.sh/acme.sh --server letsencrypt --register-account -m $email --issue -d $domain --standalone -k ec-256 --debug
~/.acme.sh/acme.sh --installcert -d $domain --fullchainpath /var/lib/marzban/xray.crt --keypath /var/lib/marzban/xray.key --ecc
wget -O /var/lib/marzban/xray_config.json "https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/xray_config.json"

#install firewall
apt install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw allow 8081/tcp
sudo ufw allow 1080/tcp
sudo ufw allow 1080/udp
sudo ufw allow 69/tcp
sudo ufw allow 69/udp
sudo ufw allow 8880/tcp
sudo ufw allow 8880/udp
sudo ufw allow $port/tcp
yes | sudo ufw enable

#install database
wget -O /var/lib/marzban/db.sqlite3 "https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/db.sqlite3"

#install WARP Proxy
wget -O /root/warp "https://raw.githubusercontent.com/hamid-gh98/x-ui-scripts/main/install_warp_proxy.sh"
sudo chmod +x /root/warp
sudo bash /root/warp -y 

#finishing
apt autoremove -y
apt clean
cd /opt/marzban
sed -i "s/# SUDO_USERNAME = \"admin\"/SUDO_USERNAME = \"${userpanel}\"/" /opt/marzban/.env
sed -i "s/# SUDO_PASSWORD = \"admin\"/SUDO_PASSWORD = \"${passpanel}\"/" /opt/marzban/.env
sed -i "s/UVICORN_PORT = 7879/UVICORN_PORT = ${port}/" /opt/marzban/.env
docker compose down && docker compose up -d
marzban cli admin import-from-env -y
sed -i "s/SUDO_USERNAME = \"${userpanel}\"/# SUDO_USERNAME = \"admin\"/" /opt/marzban/.env
sed -i "s/SUDO_PASSWORD = \"${passpanel}\"/# SUDO_PASSWORD = \"admin\"/" /opt/marzban/.env
docker compose down && docker compose up -d
cd
echo -e "${CYAN}╭═══════════════════════════════════════════════════╮${NC}" | tee -a log-install.txt
echo -e "${CYAN}│${NC}         ${NC}❖ Data login dashboard Marzban ❖${NC}          ${CYAN}│${NC}" | tee -a log-install.txt
echo -e "${CYAN}╰═══════════════════════════════════════════════════╯${NC}" | tee -a log-install.txt
echo -e "${CYAN}│❖ URL ${NC} : ${domain}:${port}/dashboard" | tee -a log-install.txt
echo -e "${CYAN}│❖ User${NC} : ${userpanel}" | tee -a log-install.txt
echo -e "${CYAN}│❖ Pass${NC} : ${passpanel}" | tee -a log-install.txt
echo -e "${CYAN}╰═══════════════════════════════════════════════════╯${NC}" | tee -a log-install.txt
clear

# Unduh skrip pelerr
echo -e "${GREEN}Mengunduh Service Token...${NC}"
sleep 1.5
curl -o /usr/local/bin/addtoken https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/addtoken >/dev/null 2>&1
chmod +x /usr/local/bin/addtoken
# Unduh skrip kontol
echo -e "${GREEN}Mengunduh Service Routing...${NC}"
sleep 1.5
curl -o /usr/local/bin/routing https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/routing >/dev/null 2>&1
chmod +x /usr/local/bin/routing
# Unduh skrip memek
echo -e "${GREEN}Mengunduh Service Hasil Routing...${NC}"
sleep 1.5
curl -o /usr/local/bin/seeroute https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/seeroute >/dev/null 2>&1
chmod +x /usr/local/bin/seeroute
# Unduh skrip es pejuh
echo -e "${GREEN}Mengunduh Service BOT Info...${NC}"
sleep 1.5
curl -o /usr/local/bin/bwbot https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/bwbot >/dev/null 2>&1
chmod +x /usr/local/bin/bwbot
# Unduh skrip es memek
echo -e "${GREEN}Mengunduh Service Speedtest...${NC}"
sleep 1.5
curl -o /usr/local/bin/ngecrot https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/ngecrot >/dev/null 2>&1
chmod +x /usr/local/bin/ngecrot
# Unduh skrip jembot bakar
echo -e "${GREEN}Mengunduh Service Change Domain...${NC}"
sleep 1.5
curl -o /usr/local/bin/gantidomain https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/gantidomain >/dev/null 2>&1
chmod +x /usr/local/bin/gantidomain
# Unduh skrip jembot
echo -e "${GREEN}Mengunduh Service BOT Usage...${NC}"
sleep 1.5
curl -o /usr/local/bin/jembot.sh https://raw.githubusercontent.com/edydevelopeler/eDYc1Nt4j3kiFoReEveRr/main/jembot.sh >/dev/null 2>&1
chmod +x /usr/local/bin/jembot.sh
# Unduh skrip memek goreng
echo -e "${GREEN}Mengunduh Service Update Script...${NC}"
sleep 1.5
curl -o /usr/local/bin/updatesc https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/updatesc >/dev/null 2>&1
chmod +x /usr/local/bin/updatesc
# Unduh skrip memek bakar
echo -e "${GREEN}Mengunduh Service Limit IP...${NC}"
sleep 1.5
curl -o /usr/local/bin/limit https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/limit >/dev/null 2>&1
chmod +x /usr/local/bin/limit
# Unduh skrip kontol goreng
echo -e "${GREEN}Mengunduh Service Restore...${NC}"
sleep 1.5
curl -o /usr/local/bin/restore https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/restore >/dev/null 2>&1
chmod +x /usr/local/bin/restore
# Download backup script
clear
echo -e "${GREEN}Mengunduh Service Backup...${NC}"
sleep 1.5
curl -o /usr/local/bin/backup https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/backup >/dev/null 2>&1
chmod +x /usr/local/bin/backup
# Download Menu
echo -e "${GREEN}Mengunduh Service Menu...${NC}"
sleep 1.5
curl -o /usr/local/bin/menu https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/menu >/dev/null 2>&1
chmod +x /usr/local/bin/menu
# Download Madngentot
echo -e "${GREEN}Mengunduh Service Rebuild VPS...${NC}"
sleep 1.5
curl -o /usr/local/bin/madngentot https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/madngentot >/dev/null 2>&1
chmod +x /usr/local/bin/madngentot
# Download template
echo -e "${GREEN}Mengunduh Service BOT Template...${NC}"
sleep 1.5
curl -o /usr/local/bin/main.py https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/main.py >/dev/null 2>&1
chmod +x /usr/local/bin/main.py
# Download template
echo -e "${GREEN}Mengunduh Service Usage VPN...${NC}"
sleep 1.5
curl -o /usr/local/bin/usage.py https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/usage.py >/dev/null 2>&1
chmod +x /usr/local/bin/usage.py
# Download warpmenu
echo -e "${GREEN}Mengunduh Service Warp...${NC}"
sleep 1.5
curl -o /usr/local/bin/warpmenu https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/warpmenu >/dev/null 2>&1
chmod +x /usr/local/bin/warpmenu
# Download apdetcore
echo -e "${GREEN}Mengunduh Service Update Core...${NC}"
sleep 1.5
curl -o /usr/local/bin/apdetcore https://raw.githubusercontent.com/helehsemvakwkwk/vivi/main/apdetcore >/dev/null 2>&1
chmod +x /usr/local/bin/apdetcore

# Tambahkan alias untuk memek ke profil shell
if ! grep -q "alias updatesc='/usr/local/bin/updatesc'" ~/.bashrc; then
    echo "alias updatesc='/usr/local/bin/updatesc'" >> ~/.bashrc
    source ~/.bashrc
fi

# Tambahkan alias untuk menu ke profil shell
if ! grep -q "alias menu='/usr/local/bin/menu'" ~/.bashrc; then
    echo "alias menu='/usr/local/bin/menu'" >> ~/.bashrc
    source ~/.bashrc
fi

echo -e "${YELLOW}Sabar beb, sedang proses pengecekan...${NC}"
sleep 2

# Send success message to Telegram
IPVPS=$(curl -s https://ipinfo.io/ip)
HOSTNAME=$(hostname)
OS=$(lsb_release -d | awk '{print $2,$3,$4}')
ISP=$(curl -s https://ipinfo.io/org | awk '{print $2,$3,$4}')
REGION=$(curl -s https://ipinfo.io/region)
DATE=$(date '+%Y-%m-%d')
TIME=$(date '+%H:%M:%S')

MESSAGE="\`\`\`
◇━━━━━━━━━━━━━━━━━◇
╭∩╮ MrZbnXIGH Project ╭∩╮
◇━━━━━━━━━━━━━━━━━◇
❖ ClientName  : $client_name
❖ Status      : Active
❖ Domain      : $domain
❖ Waktu       : $TIME
❖ Tanggal     : $DATE
❖ IP VPS      : $IPVPS
❖ Linux OS    : $OS
❖ Nama ISP    : $ISP
❖ Area ISP    : $REGION
❖ Exp SC      : $exp_date
❖ Status SC   : Registrasi
❖ Admin       : Merdeka
◇━━━━━━━━━━━━━━━━━◇
\`\`\`"

send_telegram_message "$MESSAGE"

clear
sleep 2
echo -e "${YELLOW}┌────────────────────────────────────────────────────┐\033[0m${NC}"
colorized_echo green "➽ Alhamdulillah Beb, Script telah berhasil di install."
rm /root/siti
colorized_echo magenta "➽ Sabar beb, Sedang Menghapus admin bawaan db.sqlite"
marzban cli admin delete -u admin -y
echo -e "${YELLOW}└────────────────────────────────────────────────────┘\033[0m${NC}"
sleep 1
echo -e "[\e[1;31mWARNING\e[0m]➽ Reboot dulu yuk beb biar gk error, (y/n)? "
read answer
if [ "$answer" == "${answer#[Yy]}" ] ;then
exit 0
else
cat /dev/null > ~/.bash_history && history -c && reboot
fi
